team-moabam/moabam-BE

.editorconfig
.github/workflows/ci.yml
.gitignore
build.gradle
config/checkstyle/checkstyle.xml
config/checkstyle/suppressions.xml
config/naver-checkstyle-rules.xml
config/naver-intellij-formatter-custom.xml

- #1 
- [프로젝트 초기 설정 wiki](https://github.com/team-moabam/moabam-BE/wiki/%F0%9F%90%A3-moabam-backend#%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%B4%88%EA%B8%B0-%EC%84%B8%ED%8C%85%EB%B0%A9%EB%B2%95) 문서를 반드시 참고해주세요.

chore: sonarcloud, checkstyle, jacoco 적용

---

src/main/java/com/moabam/api/dto/ModifyRoomRequest.java
src/test/java/com/moabam/api/presentation/RoomControllerTest.java

- close #33 
프론트와 논의 후 방 수정 API를 수정했습니다.

feat: 방 수정에 필요한 필드 추가

---

.github/workflows/ci.yml
.github/workflows/develop-cd.yml
Dockerfile
build.gradle
docker-compose-dev.yml
nginx/nginx.template
scripts/deploy-dev.sh
scripts/init-letsencrypt.sh
scripts/init-nginx-converter.sh
src/main/java/com/moabam/api/presentation/HealthCheckController.java

feat: ec2 dev 서버 배포 구현

---

src/docs/asciidoc/coupon.adoc
src/docs/asciidoc/notification.adoc
src/main/java/com/moabam/api/application/CouponService.java
src/main/java/com/moabam/api/presentation/CouponController.java
src/main/java/com/moabam/global/error/model/ErrorMessage.java
src/main/resources/static/docs/coupon.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notification.html
src/test/java/com/moabam/api/application/CouponServiceTest.java
src/test/java/com/moabam/api/application/NotificationServiceTest.java
src/test/java/com/moabam/api/domain/repository/NotificationRepositoryTest.java
src/test/java/com/moabam/api/presentation/CouponControllerTest.java
src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
src/test/java/com/moabam/global/common/repository/StringRedisRepositoryTest.java

feat: 쿠폰 삭제 기능 구현

---

src/main/java/com/moabam/global/config/WebConfig.java
src/main/resources/static/docs/coupon.html

This reverts commit baf4703c010e0494032d6e62e4c3f44906cfccd6.
- close #이슈번호

fix: config 수정

---

.gitignore
src/main/java/com/moabam/api/application/room/RoomCertificationService.java
src/main/java/com/moabam/api/application/room/RoomSearchService.java
src/main/java/com/moabam/api/application/room/RoomService.java
src/main/java/com/moabam/api/presentation/RoomController.java
src/main/resources/static/docs/coupon.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notification.html
src/test/java/com/moabam/api/application/RoomCertificationServiceTest.java
src/test/java/com/moabam/api/application/RoomServiceTest.java

- close #65 
* 기존 RoomService가 너무 커져서 비슷한 관심사를 가진 서비스 3개로 분리하였습니다.

refactor: 방 관련 서비스 분리

---

src/main/java/com/moabam/api/application/room/RoomService.java
src/main/java/com/moabam/api/presentation/RoomController.java
src/test/java/com/moabam/api/application/RoomServiceTest.java

- close #69 
<br>
- 기능이 아주 간단해서 이번 PR은 짧습니다!!!

feat: 방장 위임 기능 구현

---

src/main/java/com/moabam/api/domain/coupon/CouponWallet.java
src/main/java/com/moabam/api/domain/coupon/repository/CouponWalletRepository.java
src/test/java/com/moabam/api/domain/coupon/CouponWalletTest.java

feat: CouponWallet 엔티티, 레포지토리 구현

---

build.gradle
src/main/java/com/moabam/api/application/member/MemberMapper.java
src/main/java/com/moabam/api/application/member/MemberService.java
src/main/java/com/moabam/api/domain/member/Member.java
src/main/java/com/moabam/api/domain/member/repository/MemberSearchRepository.java
src/main/java/com/moabam/api/dto/member/MemberInfo.java
src/main/java/com/moabam/api/dto/member/MemberInfoSearchResponse.java
src/main/java/com/moabam/global/common/util/BaseDataCode.java
src/main/java/com/moabam/global/common/util/BaseImageUrl.java
src/main/java/com/moabam/global/error/model/ErrorMessage.java
src/test/java/com/moabam/api/application/member/MemberServiceTest.java
src/test/java/com/moabam/api/domain/entity/MemberTest.java
src/test/java/com/moabam/api/presentation/MemberAuthorizeControllerTest.java
src/test/java/com/moabam/api/presentation/MemberControllerTest.java
src/test/java/com/moabam/support/fixture/ItemFixture.java
src/test/java/com/moabam/support/fixture/MemberInfoSearchFixture.java

fix: noskin image 변경

---

src/main/java/com/moabam/api/application/item/ItemMapper.java
src/main/java/com/moabam/api/application/member/MemberService.java
src/main/java/com/moabam/api/application/room/SearchService.java
src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
src/main/java/com/moabam/api/domain/item/Item.java
src/main/java/com/moabam/api/domain/item/ItemImage.java
src/main/java/com/moabam/api/domain/member/Member.java
src/main/java/com/moabam/api/domain/room/Room.java
src/test/java/com/moabam/api/application/member/MemberServiceTest.java
src/test/java/com/moabam/api/domain/room/RoomTest.java
src/test/java/com/moabam/api/presentation/MemberControllerTest.java
src/test/java/com/moabam/support/fixture/ItemFixture.java

feat: 아이템 이미지 버전 추가 및 방 배경 업데이트

---

src/main/java/com/moabam/api/application/coupon/CouponManageService.java
src/main/java/com/moabam/api/application/coupon/CouponService.java
src/main/java/com/moabam/api/application/notification/NotificationService.java
src/main/java/com/moabam/api/domain/coupon/repository/CouponManageRepository.java
src/main/java/com/moabam/api/domain/coupon/repository/CouponRepository.java
src/main/java/com/moabam/api/infrastructure/fcm/FcmService.java
src/main/java/com/moabam/api/infrastructure/redis/ZSetRedisRepository.java
src/main/java/com/moabam/api/presentation/CouponController.java
src/main/java/com/moabam/global/config/EmbeddedRedisConfig.java
src/main/resources/static/docs/coupon.html
src/test/java/com/moabam/api/application/coupon/CouponManageServiceTest.java
src/test/java/com/moabam/api/application/coupon/CouponServiceTest.java
src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
src/test/java/com/moabam/api/domain/coupon/repository/CouponManageRepositoryTest.java
src/test/java/com/moabam/api/infrastructure/redis/ZSetRedisRepositoryTest.java
src/test/java/com/moabam/api/presentation/CouponControllerTest.java
src/test/java/com/moabam/support/fixture/CouponFixture.java

refactor: 실시간 선착순 쿠폰 발급 기능 리팩터링

---

src/main/java/com/moabam/api/application/auth/JwtAuthenticationService.java
src/main/java/com/moabam/api/application/coupon/CouponManageService.java
src/main/resources/static/docs/coupon.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notification.html
src/test/java/com/moabam/api/application/auth/JwtProviderServiceTest.java

- close #172 
`io.io.jsonwebtoken`에서 기본 인코딩 과정이 Base64Url로 되어있기 때문에 디코딩도 Base64Url 디코드로 변경하였습니다.
[관련링크](https://github.com/jwtk/jjwt)

fix: Base64관련 디코딩 코드 변경 -> Base64Url

---

src/main/java/com/moabam/api/application/room/RoomService.java
src/test/java/com/moabam/api/presentation/RoomControllerTest.java

fix: 방장 방 나가기 안되는 버그 수정

---

src/main/java/com/moabam/api/application/image/ImageService.java
src/main/java/com/moabam/api/domain/image/ImageResizer.java
src/main/java/com/moabam/api/domain/image/NewImage.java
src/main/java/com/moabam/api/dto/room/CertifyRoomRequest.java
src/main/java/com/moabam/api/dto/room/CertifyRoomsRequest.java
src/main/java/com/moabam/api/presentation/RoomController.java
src/test/java/com/moabam/api/application/image/ImageServiceTest.java

fix: 루틴 인증 사진 업로드 안되는 버그 해결

---

src/main/java/com/moabam/api/application/payment/PaymentMapper.java
src/main/java/com/moabam/api/application/payment/PaymentService.java
src/main/java/com/moabam/api/dto/payment/RequestConfirmPaymentResponse.java
src/main/java/com/moabam/api/infrastructure/payment/TossPaymentService.java
src/main/java/com/moabam/api/presentation/PaymentController.java
src/test/java/com/moabam/api/application/payment/PaymentServiceTest.java
src/test/java/com/moabam/api/presentation/PaymentControllerTest.java

fix: 토스 결제 승인 성공/실패 시 결과 반영 안되는 이슈 해결

---

src/main/java/com/moabam/api/dto/payment/ConfirmTossPaymentResponse.java
src/test/java/com/moabam/support/fixture/PaymentFixture.java

fix: approvedAt 변환 오류 수정

---

src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
src/main/java/com/moabam/api/dto/room/RoomDetailsResponse.java

refactor: 방 상세 정보에 방 생성 날짜시간 추가

---

src/main/java/com/moabam/api/application/room/CertificationService.java
src/main/java/com/moabam/api/application/room/SearchService.java

fix: 참여자 목록이 복사되는 버그 해결

---

src/main/java/com/moabam/api/application/room/SearchService.java

fix: 기여도 버그 해결

---

src/main/java/com/moabam/api/application/room/SearchService.java
src/main/java/com/moabam/api/domain/room/repository/CertificationsSearchRepository.java
src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
src/test/java/com/moabam/api/application/room/RoomServiceConcurrencyTest.java
src/test/java/com/moabam/api/application/room/SearchServiceTest.java

fix: 인증율 하락 버그 수정

---

build.gradle
src/main/java/com/moabam/api/infrastructure/payment/TossPaymentService.java
src/main/resources/logback-spring.xml

feat: 에러 로그 슬랙 연동 구현

---

src/main/java/com/moabam/api/application/room/SearchService.java

fix: date equals 적용

---

src/main/java/com/moabam/api/application/ranking/RankingMapper.java
src/main/java/com/moabam/api/application/ranking/RankingService.java

fix: 내 랭킹 조회 에러 변경

---

README.md

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? (e.g. `feat: 유저 조회 기능 구현`)
- close #이슈번호

refactor: Readme 수정
